import React from 'react';
import PageLayout from '../components/layout/PageLayout';
import useDocumentTitle from '../hooks/useDocumentTitle';

const PrivacyPolicyPage = () => {
  useDocumentTitle('Privacy Policy');

  return (
    <PageLayout>
      <div className="max-w-4xl mx-auto px-4 py-16 sm:px-6 lg:px-8">
        <div className="mb-12 text-center">
          <h1 className="text-4xl md:text-5xl font-black text-text-primary font-display tracking-tight mb-4">
            Privacy Policy
          </h1>
          <p className="text-lg text-text-muted">
            Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
          </p>
        </div>

        <div className="glass-panel shadow-premium rounded-3xl p-8 md:p-12 space-y-8 text-text-primary/90 leading-relaxed">
          <section>
            <h2 className="text-2xl font-bold text-text-primary font-display mb-4">1. Information We Collect</h2>
            <p className="mb-4">
              When you use VocaPrep, we collect information that you provide to us directly, such as when you create an account, update your profile, or interact with our AI-powered interview coach. This may include:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-text-muted">
              <li>Name and email address</li>
              <li>Audio recordings of your interview practice sessions</li>
              <li>Transcripts of your speech generated by our AI</li>
              <li>Performance metrics and feedback data</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-text-primary font-display mb-4">2. How We Use Your Information</h2>
            <p className="mb-4">
              We use the information we collect to provide, maintain, and improve our services. Specifically, your audio and transcript data are used to:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-text-muted">
              <li>Analyze your speech patterns, filler words, and pacing</li>
              <li>Generate constructive feedback using artificial intelligence</li>
              <li>Track your progress over time in your dashboard</li>
              <li>Personalize your interview questions based on your role</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-text-primary font-display mb-4">3. Data Security and AI Processing</h2>
            <p className="text-text-muted">
              We take the security of your data seriously. Your audio recordings are processed securely to generate transcripts and are not used to train public AI models without your explicit consent. We employ industry-standard security measures to protect your personal information from unauthorized access, disclosure, or destruction.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-text-primary font-display mb-4">4. Sharing of Information</h2>
            <p className="text-text-muted">
              We do not sell your personal data to third parties. We may share your information with trusted third-party service providers (such as AI processing APIs and cloud hosting) strictly for the purpose of operating our service. These providers are bound by confidentiality agreements to protect your data.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-text-primary font-display mb-4">5. Your Rights</h2>
            <p className="text-text-muted">
              You have the right to access, update, or delete your personal information at any time. You can view and manage your interview history directly from your dashboard. If you wish to permanently delete your account and all associated data, please contact our support team.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-text-primary font-display mb-4">6. Contact Us</h2>
            <p className="text-text-muted">
              If you have any questions or concerns about this Privacy Policy or our data practices, please contact us at privacy@vocaprep.com.
            </p>
          </section>
        </div>
      </div>
    </PageLayout>
  );
};

export default PrivacyPolicyPage;
